AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Template to Create Service Catalog Product for Amazon Workspaces

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Workspaces
        Parameters:
          - pCustomWorkspacesTemplateURL
Parameters:
  pCustomWorkspacesTemplateURL:
    Description: S3 URL for Amazon Workspaces Cloudformation
    Type: String
    Default: https://replace_with_your_s3_bucket.s3.eu-west-1.amazonaws.com/workspaces.yaml
  pLambdaLogGroupRetention:
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
    Default: 120
    Description: Specifies the number of days you want to retain log events
    Type: String


Resources:
  rWorkspacesProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: Workspaces
      Description: creates an Amazon Workspace
      Owner: Workspaces
      ProvisioningArtifactParameters:
        - Name: v1.0
          Info:
            LoadTemplateFromURL: !Ref pCustomWorkspacesTemplateURL

  rWorkspacesPortfolio:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      DisplayName: WorkspacesPortfolio
      ProviderName: Workspaces
      Description: Service Catalog Portfolio for Amazon Workspaces

  rWorkspacesPortfolioAssociation:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref rWorkspacesPortfolio
      ProductId: !Ref rWorkspacesProduct
